SELECT SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT
  FROM (
        SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
         , PRODUCT_ID
         , USER_ID
         , SALES_AMOUNT
      FROM ONLINE_SALE
     WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
    UNION ALL   -- 이젠 UNION ALL만 봐도 신한이 생각난다 ㅜㅜ
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
         , PRODUCT_ID
         , NULL AS USER_ID
         , SALES_AMOUNT
      FROM OFFLINE_SALE
     WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
  ) a
 ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;