SELECT p.PRODUCT_ID
     , p.PRODUCT_NAME
     , p.PRICE * SUM(o.AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT p
 INNER JOIN FOOD_ORDER o
    ON p.PRODUCT_ID = o.PRODUCT_ID
 WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
 GROUP BY p.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID;