SELECT i.REST_ID
     , i.REST_NAME
     , i.FOOD_TYPE
     , i.FAVORITES
     , i.ADDRESS
     , r.REVIEW_SCORE AS SCORE
  FROM REST_INFO i
 INNER JOIN (
        SELECT REST_ID
             , ROUND(AVG(REVIEW_SCORE), 2) AS REVIEW_SCORE
          FROM REST_REVIEW r
         GROUP BY REST_ID
     ) r
    ON i.REST_ID = r.REST_ID
 WHERE SUBSTRING(i.ADDRESS,1,2) = '서울'
 ORDER BY r.REVIEW_SCORE DESC, i.FAVORITES DESC;