SELECT FLAVOR
  FROM (
    SELECT FLAVOR
         , SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM (
        SELECT FLAVOR
             , TOTAL_ORDER
          FROM FIRST_HALF
         UNION ALL
        SELECT FLAVOR
             , TOTAL_ORDER
          FROM JULY
      ) a
     GROUP BY FLAVOR
  ) b
 ORDER BY TOTAL_ORDER DESC
 LIMIT 3;