SELECT MONTH(START_DATE) AS MONTH
     , CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE CAR_ID IN (
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE DATEDIFF(START_DATE, '2022-10-31') <= 0
       AND DATEDIFF(START_DATE, '2022-08-01') >= 0
     GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
 )
   AND DATEDIFF(START_DATE, '2022-10-31') <= 0
   AND DATEDIFF(START_DATE, '2022-08-01') >= 0
 GROUP BY MONTH, CAR_ID
 ORDER BY MONTH, CAR_ID DESC;