SELECT p.PRODUCT_CODE, p.PRICE*SUM(s.SALES_AMOUNT) AS SALES
  FROM PRODUCT p
 INNER JOIN OFFLINE_SALE s
    ON p.PRODUCT_ID = s.PRODUCT_ID
 GROUP BY p.PRODUCT_ID
 ORDER BY p.PRICE*SUM(s.SALES_AMOUNT) DESC, PRODUCT_CODE;