SELECT WRITER_ID AS USER_ID
     , (SELECT NICKNAME FROM USED_GOODS_USER WHERE WRITER_ID = USER_ID) AS NICKNAME
     , SUM(PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD
 WHERE STATUS = 'DONE'
 GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES;