SELECT b.CATEGORY, sum(s.SALES) AS TOTAL_SALES
  FROM BOOK b
 INNER JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
 WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
 GROUP BY b.CATEGORY
 ORDER BY b.CATEGORY;
